import { ArrowRight, Check } from "lucide-react";
import { WhiteFooter, WhiteHeader, WhiteSubhero } from "../white-shell";

const offer=[
 {n:"01",label:"Dział projektowy",image:"/assets/3d-silesia-granat.png",alt:"3D SILESIA",title:"Projektowanie wnętrz",text:"Od analizy układu po kompletną dokumentację — projektujemy wnętrza, które są spójne, funkcjonalne i możliwe do wykonania w ustalonym budżecie.",points:["Układy funkcjonalne i koncepcja wnętrza","Dobór materiałów, kolorów i oświetlenia","Wizualizacje oraz dokumentacja techniczna"]},
 {n:"02",label:"Dział produkcyjny",image:"/assets/ms-meble-granat.png",alt:"MS Meble Szymkowiak",title:"Meble na wymiar",text:"Projektujemy i wykonujemy zabudowy jako integralną część całego wnętrza, z dbałością o ergonomię, materiały i dopracowany montaż.",points:["Kuchnie, garderoby, szafy i zabudowy","Dobór płyt, frontów, blatów i okuć","Produkcja, dostawa i profesjonalny montaż"]},
 {n:"03",label:"Dział wykonawczy",image:"/assets/kimpro-granat.png",alt:"KIMPRO",title:"Kompleksowe wykończenia",text:"Prowadzimy realizację od stanu deweloperskiego do gotowego wnętrza, koordynując kolejne etapy i pilnując zgodności prac z projektem.",points:["Harmonogram, materiały i koordynacja prac","Prace instalacyjne, budowlane i wykończeniowe","Stały nadzór nad zgodnością z projektem"]},
 {n:"04",label:"Niezależna kontrola",image:"/assets/tube-inspektor-granat.png",alt:"TUBE INSPEKTOR",title:"Odbiory techniczne",text:"Niezależnie weryfikujemy wykonane prace wykończeniowe, stan urządzeń oraz prawidłowość realizacji deweloperskich i indywidualnych.",points:["Odbiory mieszkań od dewelopera","Kontrola prac wykończeniowych i meblowych","Wskazanie usterek i dokumentacja kontroli"]},
];
const packages=[
 {name:"Standard",label:"Dobra jakość w kontrolowanym budżecie",costLabel:"Priorytet wariantu",cost:"Cena wybranych materiałów i najlepszy możliwy stosunek jakości do kosztu. Przeanalizujemy szeroką ofertę rynkową, aby znaleźć rozwiązania optymalne jakościowo i cenowo.",image:"/assets/standard.jpg",description:"Już na starcie wyróżniają nas wiedza i współdziałanie w pełnej skali inwestycji. Zaprojektujemy rozwiązania możliwe do wykonania bez nadmiernych kosztów, z materiałów opłacalnych w tym wariancie, i dopracujemy każdy szczegół — analizując nawet układ gresu w łazience pod kątem ograniczenia odpadów.",design:["Aranżacja podporządkowana optymalizacji kosztów","Dobre materiały wyszukane w korzystnych źródłach","Rozwiązania dopasowane do realnych możliwości budżetu"],furniture:["Płyty meblowe i blaty laminowane","Ekonomiczne linie okuć uznanych producentów","Akcesoria krajowych producentów i maksymalnie uproszczona zabudowa","Zawsze najwyższy, niezmienny poziom wykonania"],finishing:["Optymalne i sprawdzone technologie","Trwałość ważniejsza od krótkotrwałych trendów","Funkcjonalność i standard wykonania na najwyższym poziomie"]},
 {name:"Plus",label:"Wyższy standard i efektowniejsze wykończenie",costLabel:"Priorytet wariantu",cost:"Równowaga między efektownym wyglądem a racjonalnym wykorzystaniem budżetu. Inwestujemy przede wszystkim w rozwiązania, które realnie podnoszą estetykę, komfort i trwałość wnętrza.",image:"/assets/plus.jpg",featured:true,description:"Projekt i realizację prowadzimy wspólnie od pierwszych decyzji. Dobieramy materiały z wyższej półki i efektowniejsze wykończenia, a rozwiązania ekskluzywne stosujemy wybiórczo — tam, gdzie najmocniej podnoszą jakość wnętrza i tworzą efekt WOW bez niekontrolowanego wzrostu kosztów.",design:["Rozwinięta koncepcja materiałowa i kolorystyczna","Większa swoboda w kształtowaniu detali","Ekskluzywne akcenty stosowane w kluczowych miejscach"],furniture:["Fronty lakierowane lub akrylowe","Smukłe blaty kompaktowe i okucia wyższej klasy","Ryflowania, przeszklenia lub dekoracyjne podświetlenie"],finishing:["Efektowniejsze materiały i staranniejsze detale","Rozbudowane rozwiązania oświetleniowe","Świadome łączenie kolorów, faktur i powierzchni"]},
 {name:"Premium",label:"Indywidualny charakter bez standardowych ograniczeń",costLabel:"Priorytet wariantu",cost:"Pełna indywidualizacja, najwyższa jakość materiałów i bezkompromisowe dopracowanie detali. Każde rozwiązanie podporządkowujemy spójności projektu oraz wyjątkowemu efektowi końcowemu.",image:"/assets/premium-wood-kitchen.png",description:"Całą inwestycję traktujemy jako jeden spójny projekt, w którym architektura wnętrza, zabudowy i wykonanie powstają równolegle. Indywidualne rozwiązania dopracowujemy technicznie przed realizacją, koordynując materiały, podziały, światło i detale tak, aby efekt końcowy był unikalny i bezkompromisowy.",design:["Autorska koncepcja przygotowana dla konkretnego wnętrza","Pełna personalizacja form, materiałów i detali","Rozwiązania projektowane indywidualnie, poza standardowym katalogiem"],furniture:["Fornir, lakier premium, szkło, metal i tapicerka","Kamień naturalny, spiek oraz elementy wykonywane na zamówienie","Najwyższej klasy okucia i zintegrowane oświetlenie"],finishing:["Szlachetne materiały i nietypowe technologie","Indywidualne zabudowy i dekoracyjne elementy wykonawcze","Precyzyjne łączenie faktur, kolorów oraz światła"]},
];
export default function OfferPage(){return <main className="white-site offer-page"><WhiteHeader/><WhiteSubhero eyebrow="OFERTA KIM SILESIA" title={<>Od koncepcji<br/><em>do gotowego wnętrza.</em></>} text="Wybierz pojedynczą usługę albo powierz nam cały proces." image="/assets/bialy-hero-kuchnia.png"/>
 <section className="offer-departments"><header><div><small>CZTERY OBSZARY WSPÓŁPRACY</small><h2>Wszystko, czego potrzebuje<br/>Twoje wnętrze.</h2></div><p>Możesz wybrać jeden zakres albo połączyć działy w spójny proces — od pierwszej koncepcji, przez produkcję i wykonanie, aż po niezależną kontrolę jakości.</p></header><div className="offer-department-grid">{offer.map(({n,label,image,alt,title,text,points})=><article key={n}><div className="offer-department-top"><span>{n}</span><img className="offer-department-logo" src={image} alt={alt}/><small>{label}</small></div><h3>{title}</h3><p>{text}</p><ul>{points.map(point=><li key={point}><Check/>{point}</li>)}</ul><a href="/bialy/kontakt" aria-label={`Zapytaj o ${title}`}>Zapytaj o usługę <ArrowRight/></a></article>)}</div></section>
 <section className="offer-packages"><header><div><small>TRZY STANDARDY WYKOŃCZENIA</small><h2>Wybierz wariant<br/>dopasowany do budżetu.</h2></div><p>Każdy wariant zachowuje ten sam przemyślany układ funkcjonalny. Różnice dotyczą materiałów, wyposażenia, detali i zakresu personalizacji.</p></header><div className="package-grid">{packages.map(p=><article className={p.featured?"featured":""} key={p.name}>{p.featured&&<b className="package-choice">NAJCZĘŚCIEJ WYBIERANY</b>}<figure><img src={p.image} alt={`Wizualizacja wariantu ${p.name}`}/></figure><div className="package-body"><small>{p.label}</small><h3>{p.name}</h3><div className="package-index"><span>{p.costLabel}</span><strong>{p.cost}</strong></div><p>{p.description}</p><div className="package-scopes"><section><h4>Przygotowanie aranżacji projektowej</h4><ul>{p.design.map(i=><li key={i}><Check/>{i}</li>)}</ul></section><section><h4>Meble na wymiar</h4><ul>{p.furniture.map(i=><li key={i}><Check/>{i}</li>)}</ul></section><section><h4>Prace wykończeniowe</h4><ul>{p.finishing.map(i=><li key={i}><Check/>{i}</li>)}</ul></section></div><a href={`/bialy/kontakt?wariant=${p.name.toLowerCase()}`}>Zapytaj o wariant <ArrowRight/></a></div></article>)}</div><p className="package-disclaimer"><b>Każdy wariant określa priorytet projektowy i przykładowy standard rozwiązań — nie stanowi gotowego cennika.</b> Ostateczna wycena zależy od projektu, wymiarów, wybranych materiałów i zakresu opracowania.</p></section>
 <section className="offer-note"><div><small>Zakres dopasowany do Ciebie</small><h2>Możemy przejąć całość<br/>albo wybrany etap.</h2></div><p>Po pierwszej rozmowie określimy potrzeby, kolejność prac i realny zakres budżetu. Otrzymasz jasną propozycję dalszego działania — bez niepotrzebnego komplikowania procesu.</p></section><WhiteFooter/></main>}
